# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.frame_association_api import FrameAssociationApi  # noqa: E501
from tator.rest import ApiException


class TestFrameAssociationApi(unittest.TestCase):
    """FrameAssociationApi unit test stubs"""

    def setUp(self):
        self.api = api.frame_association_api.FrameAssociationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_frame_association(self):
        """Test case for delete_frame_association

        """
        pass

    def test_get_frame_association(self):
        """Test case for get_frame_association

        """
        pass

    def test_update_frame_association(self):
        """Test case for update_frame_association

        """
        pass


if __name__ == '__main__':
    unittest.main()
