# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.localization_spec_one_of2 import LocalizationSpecOneOf2  # noqa: E501
from tator.rest import ApiException

class TestLocalizationSpecOneOf2(unittest.TestCase):
    """LocalizationSpecOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LocalizationSpecOneOf2
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.localization_spec_one_of2.LocalizationSpecOneOf2()  # noqa: E501
        if include_optional :
            return LocalizationSpecOneOf2(
                media_id = 56, 
                modified = True, 
                type = 56, 
                version = 56, 
                x = 0.0, 
                y = 0.0
            )
        else :
            return LocalizationSpecOneOf2(
                media_id = 56,
                type = 56,
                x = 0.0,
                y = 0.0,
        )

    def testLocalizationSpecOneOf2(self):
        """Test LocalizationSpecOneOf2"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
