# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.analysis_api import AnalysisApi  # noqa: E501
from tator.rest import ApiException


class TestAnalysisApi(unittest.TestCase):
    """AnalysisApi unit test stubs"""

    def setUp(self):
        self.api = api.analysis_api.AnalysisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_analysis(self):
        """Test case for create_analysis

        """
        pass

    def test_get_analysis_list(self):
        """Test case for get_analysis_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
