# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.leaf_type import LeafType  # noqa: E501
from tator.rest import ApiException


class TestLeafType(unittest.TestCase):
    """LeafType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLeafType(self):
        """Test LeafType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.leaf_type.LeafType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
