# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.body17 import Body17  # noqa: E501
from tator.rest import ApiException


class TestBody17(unittest.TestCase):
    """Body17 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody17(self):
        """Test Body17"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.body17.Body17()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
