# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.inline_response2012 import InlineResponse2012  # noqa: E501
from tator.rest import ApiException

class TestInlineResponse2012(unittest.TestCase):
    """InlineResponse2012 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse2012
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.inline_response2012.InlineResponse2012()  # noqa: E501
        if include_optional :
            return InlineResponse2012(
                id = 1, 
                message = '0'
            )
        else :
            return InlineResponse2012(
        )

    def testInlineResponse2012(self):
        """Test InlineResponse2012"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
