# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.inline_response20010 import InlineResponse20010  # noqa: E501
from tator.rest import ApiException


class TestInlineResponse20010(unittest.TestCase):
    """InlineResponse20010 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20010(self):
        """Test InlineResponse20010"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.inline_response20010.InlineResponse20010()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
