# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.attribute_type_update import AttributeTypeUpdate  # noqa: E501
from tator.rest import ApiException


class TestAttributeTypeUpdate(unittest.TestCase):
    """AttributeTypeUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttributeTypeUpdate(self):
        """Test AttributeTypeUpdate"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.attribute_type_update.AttributeTypeUpdate()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
