# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.localization_spec import LocalizationSpec  # noqa: E501
from tator.rest import ApiException

class TestLocalizationSpec(unittest.TestCase):
    """LocalizationSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test LocalizationSpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.localization_spec.LocalizationSpec()  # noqa: E501
        if include_optional :
            return LocalizationSpec(
                attributes = { }, 
                frame = 56, 
                height = 0.0, 
                media_id = 56, 
                modified = True, 
                parent = 1.337, 
                type = 56, 
                u = -1.0, 
                v = -1.0, 
                version = 56, 
                width = 0.0, 
                x = 0.0, 
                y = 0.0
            )
        else :
            return LocalizationSpec(
                frame = 56,
                media_id = 56,
                type = 56,
        )

    def testLocalizationSpec(self):
        """Test LocalizationSpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
