# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.dot import Dot  # noqa: E501
from tator.rest import ApiException

class TestDot(unittest.TestCase):
    """Dot unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Dot
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.dot.Dot()  # noqa: E501
        if include_optional :
            return Dot(
                attributes = { }, 
                email = '0', 
                frame = 56, 
                id = 56, 
                media = 56, 
                meta = 56, 
                modified = True, 
                project = 56, 
                thumbnail_image = '0', 
                version = 56, 
                x = 0.0, 
                y = 0.0
            )
        else :
            return Dot(
        )

    def testDot(self):
        """Test Dot"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
