# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.one_ofinline_response20028_columns_items import OneOfinlineResponse20028ColumnsItems  # noqa: E501
from tator.rest import ApiException


class TestOneOfinlineResponse20028ColumnsItems(unittest.TestCase):
    """OneOfinlineResponse20028ColumnsItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse20028ColumnsItems(self):
        """Test OneOfinlineResponse20028ColumnsItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.one_ofinline_response20028_columns_items.OneOfinlineResponse20028ColumnsItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
