# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.inline_response2043 import InlineResponse2043  # noqa: E501
from tator.rest import ApiException


class TestInlineResponse2043(unittest.TestCase):
    """InlineResponse2043 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2043(self):
        """Test InlineResponse2043"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.inline_response2043.InlineResponse2043()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
