# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.user_api import UserApi  # noqa: E501
from tator.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user(self):
        """Test case for get_user

        """
        pass

    def test_update_user(self):
        """Test case for update_user

        """
        pass

    def test_who_am_i(self):
        """Test case for who_am_i

        """
        pass


if __name__ == '__main__':
    unittest.main()
