# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.tree_leaf_api import TreeLeafApi  # noqa: E501
from tator.rest import ApiException


class TestTreeLeafApi(unittest.TestCase):
    """TreeLeafApi unit test stubs"""

    def setUp(self):
        self.api = api.tree_leaf_api.TreeLeafApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_tree_leaf(self):
        """Test case for create_tree_leaf

        """
        pass

    def test_delete_tree_leaf(self):
        """Test case for delete_tree_leaf

        """
        pass

    def test_delete_tree_leaf_list(self):
        """Test case for delete_tree_leaf_list

        """
        pass

    def test_get_tree_leaf(self):
        """Test case for get_tree_leaf

        """
        pass

    def test_get_tree_leaf_list(self):
        """Test case for get_tree_leaf_list

        """
        pass

    def test_tree_leaf_suggestion(self):
        """Test case for tree_leaf_suggestion

        """
        pass

    def test_update_tree_leaf(self):
        """Test case for update_tree_leaf

        """
        pass

    def test_update_tree_leaf_list(self):
        """Test case for update_tree_leaf_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
