# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.inline_response2041 import InlineResponse2041  # noqa: E501
from tator.rest import ApiException


class TestInlineResponse2041(unittest.TestCase):
    """InlineResponse2041 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2041(self):
        """Test InlineResponse2041"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.inline_response2041.InlineResponse2041()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
