# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.localization_type_api import LocalizationTypeApi  # noqa: E501
from tator.rest import ApiException


class TestLocalizationTypeApi(unittest.TestCase):
    """LocalizationTypeApi unit test stubs"""

    def setUp(self):
        self.api = api.localization_type_api.LocalizationTypeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_localization_type(self):
        """Test case for create_localization_type

        """
        pass

    def test_delete_localization_type(self):
        """Test case for delete_localization_type

        """
        pass

    def test_get_localization_type(self):
        """Test case for get_localization_type

        """
        pass

    def test_get_localization_type_list(self):
        """Test case for get_localization_type_list

        """
        pass

    def test_update_localization_type(self):
        """Test case for update_localization_type

        """
        pass


if __name__ == '__main__':
    unittest.main()
