# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.analysis_spec import AnalysisSpec  # noqa: E501
from tator.rest import ApiException


class TestAnalysisSpec(unittest.TestCase):
    """AnalysisSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAnalysisSpec(self):
        """Test AnalysisSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.analysis_spec.AnalysisSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
