# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.algorithm_api import AlgorithmApi  # noqa: E501
from tator.rest import ApiException


class TestAlgorithmApi(unittest.TestCase):
    """AlgorithmApi unit test stubs"""

    def setUp(self):
        self.api = api.algorithm_api.AlgorithmApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_algorithm_launch(self):
        """Test case for algorithm_launch

        """
        pass

    def test_get_algorithm_list(self):
        """Test case for get_algorithm_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
