# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.inline_response20027 import InlineResponse20027  # noqa: E501
from tator.rest import ApiException


class TestInlineResponse20027(unittest.TestCase):
    """InlineResponse20027 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20027(self):
        """Test InlineResponse20027"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.inline_response20027.InlineResponse20027()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
