# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.body32 import Body32  # noqa: E501
from tator.rest import ApiException


class TestBody32(unittest.TestCase):
    """Body32 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody32(self):
        """Test Body32"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.body32.Body32()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
