# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.inline_response2013 import InlineResponse2013  # noqa: E501
from tator.rest import ApiException


class TestInlineResponse2013(unittest.TestCase):
    """InlineResponse2013 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2013(self):
        """Test InlineResponse2013"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.inline_response2013.InlineResponse2013()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
