# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.inline_object19 import InlineObject19  # noqa: E501
from tator.rest import ApiException

class TestInlineObject19(unittest.TestCase):
    """InlineObject19 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineObject19
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.inline_object19.InlineObject19()  # noqa: E501
        if include_optional :
            return InlineObject19(
                gid = '0', 
                md5 = '0', 
                name = '0', 
                section = '0', 
                type = 56, 
                uid = '0', 
                url = '0'
            )
        else :
            return InlineObject19(
                gid = '0',
                md5 = '0',
                name = '0',
                section = '0',
                type = 56,
                uid = '0',
                url = '0',
        )

    def testInlineObject19(self):
        """Test InlineObject19"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
