# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.get_clip_api import GetClipApi  # noqa: E501
from tator.rest import ApiException


class TestGetClipApi(unittest.TestCase):
    """GetClipApi unit test stubs"""

    def setUp(self):
        self.api = api.get_clip_api.GetClipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_retrieve_get_clip_api(self):
        """Test case for retrieve_get_clip_api

        """
        pass


if __name__ == '__main__':
    unittest.main()
