# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.entity_type_schema import EntityTypeSchema  # noqa: E501
from tator.rest import ApiException

class TestEntityTypeSchema(unittest.TestCase):
    """EntityTypeSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test EntityTypeSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.entity_type_schema.EntityTypeSchema()  # noqa: E501
        if include_optional :
            return EntityTypeSchema(
                description = '0', 
                name = '0', 
                required_fields = { }
            )
        else :
            return EntityTypeSchema(
        )

    def testEntityTypeSchema(self):
        """Test EntityTypeSchema"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
