# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.one_ofinline_response200_columns_items import OneOfinlineResponse200ColumnsItems  # noqa: E501
from tator.rest import ApiException


class TestOneOfinlineResponse200ColumnsItems(unittest.TestCase):
    """OneOfinlineResponse200ColumnsItems unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfinlineResponse200ColumnsItems(self):
        """Test OneOfinlineResponse200ColumnsItems"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.one_ofinline_response200_columns_items.OneOfinlineResponse200ColumnsItems()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
