# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from models.localization_list import LocalizationList  # noqa: E501
from tator.rest import ApiException


class TestLocalizationList(unittest.TestCase):
    """LocalizationList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLocalizationList(self):
        """Test LocalizationList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = tator.models.localization_list.LocalizationList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
