# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.algorithm_launch import AlgorithmLaunch  # noqa: E501
from tator.rest import ApiException

class TestAlgorithmLaunch(unittest.TestCase):
    """AlgorithmLaunch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test AlgorithmLaunch
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.algorithm_launch.AlgorithmLaunch()  # noqa: E501
        if include_optional :
            return AlgorithmLaunch(
                group_id = '0', 
                message = '0', 
                run_uids = [
                    '0'
                    ]
            )
        else :
            return AlgorithmLaunch(
        )

    def testAlgorithmLaunch(self):
        """Test AlgorithmLaunch"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
