# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import tator
from api.membership_api import MembershipApi  # noqa: E501
from tator.rest import ApiException


class TestMembershipApi(unittest.TestCase):
    """MembershipApi unit test stubs"""

    def setUp(self):
        self.api = api.membership_api.MembershipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_membership(self):
        """Test case for create_membership

        """
        pass

    def test_delete_membership(self):
        """Test case for delete_membership

        """
        pass

    def test_get_membership(self):
        """Test case for get_membership

        """
        pass

    def test_get_membership_list(self):
        """Test case for get_membership_list

        """
        pass

    def test_update_membership(self):
        """Test case for update_membership

        """
        pass


if __name__ == '__main__':
    unittest.main()
