# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import tator
from tator.models.many_spec import ManySpec  # noqa: E501
from tator.rest import ApiException

class TestManySpec(unittest.TestCase):
    """ManySpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ManySpec
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = tator.models.many_spec.ManySpec()  # noqa: E501
        if include_optional :
            return ManySpec(
                frame = 56, 
                many = [
                    null
                    ], 
                media_id = 56, 
                modified = True, 
                type = 56, 
                version = 56
            )
        else :
            return ManySpec(
                many = [
                    null
                    ],
                media_id = 56,
                type = 56,
        )

    def testManySpec(self):
        """Test ManySpec"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
