# coding: utf-8

# flake8: noqa
"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from tator_openapi.models.algorithm import Algorithm
from tator_openapi.models.algorithm_launch import AlgorithmLaunch
from tator_openapi.models.algorithm_launch_spec import AlgorithmLaunchSpec
from tator_openapi.models.analysis import Analysis
from tator_openapi.models.analysis_spec import AnalysisSpec
from tator_openapi.models.attribute_bulk_update import AttributeBulkUpdate
from tator_openapi.models.attribute_type import AttributeType
from tator_openapi.models.audio_definition import AudioDefinition
from tator_openapi.models.autocomplete_service import AutocompleteService
from tator_openapi.models.bad_request_response import BadRequestResponse
from tator_openapi.models.color_map import ColorMap
from tator_openapi.models.create_list_response import CreateListResponse
from tator_openapi.models.create_response import CreateResponse
from tator_openapi.models.credentials import Credentials
from tator_openapi.models.image_spec import ImageSpec
from tator_openapi.models.leaf import Leaf
from tator_openapi.models.leaf_spec import LeafSpec
from tator_openapi.models.leaf_suggestion import LeafSuggestion
from tator_openapi.models.leaf_type import LeafType
from tator_openapi.models.leaf_type_spec import LeafTypeSpec
from tator_openapi.models.leaf_type_update import LeafTypeUpdate
from tator_openapi.models.leaf_update import LeafUpdate
from tator_openapi.models.localization import Localization
from tator_openapi.models.localization_spec import LocalizationSpec
from tator_openapi.models.localization_type import LocalizationType
from tator_openapi.models.localization_type_spec import LocalizationTypeSpec
from tator_openapi.models.localization_type_update import LocalizationTypeUpdate
from tator_openapi.models.localization_update import LocalizationUpdate
from tator_openapi.models.media import Media
from tator_openapi.models.media_files import MediaFiles
from tator_openapi.models.media_next import MediaNext
from tator_openapi.models.media_prev import MediaPrev
from tator_openapi.models.media_type import MediaType
from tator_openapi.models.media_type_spec import MediaTypeSpec
from tator_openapi.models.media_type_update import MediaTypeUpdate
from tator_openapi.models.media_update import MediaUpdate
from tator_openapi.models.membership import Membership
from tator_openapi.models.membership_spec import MembershipSpec
from tator_openapi.models.membership_update import MembershipUpdate
from tator_openapi.models.message_response import MessageResponse
from tator_openapi.models.not_found_response import NotFoundResponse
from tator_openapi.models.notify_spec import NotifySpec
from tator_openapi.models.progress_spec import ProgressSpec
from tator_openapi.models.progress_summary_spec import ProgressSummarySpec
from tator_openapi.models.project import Project
from tator_openapi.models.project_spec import ProjectSpec
from tator_openapi.models.state import State
from tator_openapi.models.state_spec import StateSpec
from tator_openapi.models.state_type import StateType
from tator_openapi.models.state_type_spec import StateTypeSpec
from tator_openapi.models.state_type_update import StateTypeUpdate
from tator_openapi.models.state_update import StateUpdate
from tator_openapi.models.temporary_file import TemporaryFile
from tator_openapi.models.temporary_file_spec import TemporaryFileSpec
from tator_openapi.models.token import Token
from tator_openapi.models.transcode import Transcode
from tator_openapi.models.transcode_spec import TranscodeSpec
from tator_openapi.models.user import User
from tator_openapi.models.user_update import UserUpdate
from tator_openapi.models.version import Version
from tator_openapi.models.version_spec import VersionSpec
from tator_openapi.models.version_update import VersionUpdate
from tator_openapi.models.video_definition import VideoDefinition
from tator_openapi.models.video_spec import VideoSpec
from tator_openapi.models.video_update import VideoUpdate
