# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tator_openapi.configuration import Configuration


class LeafType(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'attribute_types': 'list[AttributeType]',
        'description': 'str',
        'dtype': 'str',
        'id': 'int',
        'name': 'str',
        'project': 'int'
    }

    attribute_map = {
        'attribute_types': 'attribute_types',
        'description': 'description',
        'dtype': 'dtype',
        'id': 'id',
        'name': 'name',
        'project': 'project'
    }

    def __init__(self, attribute_types=None, description='', dtype=None, id=None, name=None, project=None, local_vars_configuration=None):  # noqa: E501
        """LeafType - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._attribute_types = None
        self._description = None
        self._dtype = None
        self._id = None
        self._name = None
        self._project = None
        self.discriminator = None

        if attribute_types is not None:
            self.attribute_types = attribute_types
        if description is not None:
            self.description = description
        if dtype is not None:
            self.dtype = dtype
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if project is not None:
            self.project = project

    @property
    def attribute_types(self):
        """Gets the attribute_types of this LeafType.  # noqa: E501

        Attribute type definitions.  # noqa: E501

        :return: The attribute_types of this LeafType.  # noqa: E501
        :rtype: list[AttributeType]
        """
        return self._attribute_types

    @attribute_types.setter
    def attribute_types(self, attribute_types):
        """Sets the attribute_types of this LeafType.

        Attribute type definitions.  # noqa: E501

        :param attribute_types: The attribute_types of this LeafType.  # noqa: E501
        :type attribute_types: list[AttributeType]
        """

        self._attribute_types = attribute_types

    @property
    def description(self):
        """Gets the description of this LeafType.  # noqa: E501

        Description of the leaf type.  # noqa: E501

        :return: The description of this LeafType.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this LeafType.

        Description of the leaf type.  # noqa: E501

        :param description: The description of this LeafType.  # noqa: E501
        :type description: str
        """

        self._description = description

    @property
    def dtype(self):
        """Gets the dtype of this LeafType.  # noqa: E501

        Name of this data type, value is always \"leaf\".  # noqa: E501

        :return: The dtype of this LeafType.  # noqa: E501
        :rtype: str
        """
        return self._dtype

    @dtype.setter
    def dtype(self, dtype):
        """Sets the dtype of this LeafType.

        Name of this data type, value is always \"leaf\".  # noqa: E501

        :param dtype: The dtype of this LeafType.  # noqa: E501
        :type dtype: str
        """

        self._dtype = dtype

    @property
    def id(self):
        """Gets the id of this LeafType.  # noqa: E501

        Unique integer identifying a leaf type.  # noqa: E501

        :return: The id of this LeafType.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this LeafType.

        Unique integer identifying a leaf type.  # noqa: E501

        :param id: The id of this LeafType.  # noqa: E501
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this LeafType.  # noqa: E501

        Name of the leaf type.  # noqa: E501

        :return: The name of this LeafType.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LeafType.

        Name of the leaf type.  # noqa: E501

        :param name: The name of this LeafType.  # noqa: E501
        :type name: str
        """

        self._name = name

    @property
    def project(self):
        """Gets the project of this LeafType.  # noqa: E501

        Unique integer identifying project for this leaf type.  # noqa: E501

        :return: The project of this LeafType.  # noqa: E501
        :rtype: int
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this LeafType.

        Unique integer identifying project for this leaf type.  # noqa: E501

        :param project: The project of this LeafType.  # noqa: E501
        :type project: int
        """

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LeafType):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LeafType):
            return True

        return self.to_dict() != other.to_dict()
