# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tator_openapi.configuration import Configuration


class MediaPrev(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'prev': 'int'
    }

    attribute_map = {
        'prev': 'prev'
    }

    def __init__(self, prev=None, local_vars_configuration=None):  # noqa: E501
        """MediaPrev - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._prev = None
        self.discriminator = None

        if prev is not None:
            self.prev = prev

    @property
    def prev(self):
        """Gets the prev of this MediaPrev.  # noqa: E501


        :return: The prev of this MediaPrev.  # noqa: E501
        :rtype: int
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this MediaPrev.


        :param prev: The prev of this MediaPrev.  # noqa: E501
        :type prev: int
        """
        if (self.local_vars_configuration.client_side_validation and
                prev is not None and prev < 0):  # noqa: E501
            raise ValueError("Invalid value for `prev`, must be a value greater than or equal to `0`")  # noqa: E501

        self._prev = prev

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MediaPrev):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MediaPrev):
            return True

        return self.to_dict() != other.to_dict()
