# coding: utf-8

"""
    Tator REST API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class InlineResponse20012Type(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'description': 'str',
        'id': 'int',
        'name': 'str',
        'project': 'int'
    }

    attribute_map = {
        'description': 'description',
        'id': 'id',
        'name': 'name',
        'project': 'project'
    }

    def __init__(self, description='', id=None, name=None, project=None):  # noqa: E501
        """InlineResponse20012Type - a model defined in Swagger"""  # noqa: E501
        self._description = None
        self._id = None
        self._name = None
        self._project = None
        self.discriminator = None
        if description is not None:
            self.description = description
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if project is not None:
            self.project = project

    @property
    def description(self):
        """Gets the description of this InlineResponse20012Type.  # noqa: E501

        Description of the tree leaf type.  # noqa: E501

        :return: The description of this InlineResponse20012Type.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this InlineResponse20012Type.

        Description of the tree leaf type.  # noqa: E501

        :param description: The description of this InlineResponse20012Type.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def id(self):
        """Gets the id of this InlineResponse20012Type.  # noqa: E501

        Unique integer identifying a tree leaf type.  # noqa: E501

        :return: The id of this InlineResponse20012Type.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this InlineResponse20012Type.

        Unique integer identifying a tree leaf type.  # noqa: E501

        :param id: The id of this InlineResponse20012Type.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this InlineResponse20012Type.  # noqa: E501

        Name of the tree leaf type.  # noqa: E501

        :return: The name of this InlineResponse20012Type.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this InlineResponse20012Type.

        Name of the tree leaf type.  # noqa: E501

        :param name: The name of this InlineResponse20012Type.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def project(self):
        """Gets the project of this InlineResponse20012Type.  # noqa: E501

        Unique integer identifying project for this tree leaf type.  # noqa: E501

        :return: The project of this InlineResponse20012Type.  # noqa: E501
        :rtype: int
        """
        return self._project

    @project.setter
    def project(self, project):
        """Sets the project of this InlineResponse20012Type.

        Unique integer identifying project for this tree leaf type.  # noqa: E501

        :param project: The project of this InlineResponse20012Type.  # noqa: E501
        :type: int
        """

        self._project = project

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InlineResponse20012Type, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineResponse20012Type):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
