# coding: utf-8

"""
    Tator REST API

    Interface to the Tator backend.  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from tator.configuration import Configuration


class LocalizationAssociationUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'color': 'str',
        'localizations': 'list[int]'
    }

    attribute_map = {
        'color': 'color',
        'localizations': 'localizations'
    }

    def __init__(self, color=None, localizations=None, local_vars_configuration=None):  # noqa: E501
        """LocalizationAssociationUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._color = None
        self._localizations = None
        self.discriminator = None

        if color is not None:
            self.color = color
        if localizations is not None:
            self.localizations = localizations

    @property
    def color(self):
        """Gets the color of this LocalizationAssociationUpdate.  # noqa: E501

        A six digit hex-code Color to represent this association in the UI. If not given a color is used from a predefined progression.  # noqa: E501

        :return: The color of this LocalizationAssociationUpdate.  # noqa: E501
        :rtype: str
        """
        return self._color

    @color.setter
    def color(self, color):
        """Sets the color of this LocalizationAssociationUpdate.

        A six digit hex-code Color to represent this association in the UI. If not given a color is used from a predefined progression.  # noqa: E501

        :param color: The color of this LocalizationAssociationUpdate.  # noqa: E501
        :type: str
        """

        self._color = color

    @property
    def localizations(self):
        """Gets the localizations of this LocalizationAssociationUpdate.  # noqa: E501

        List of localization IDs.  # noqa: E501

        :return: The localizations of this LocalizationAssociationUpdate.  # noqa: E501
        :rtype: list[int]
        """
        return self._localizations

    @localizations.setter
    def localizations(self, localizations):
        """Sets the localizations of this LocalizationAssociationUpdate.

        List of localization IDs.  # noqa: E501

        :param localizations: The localizations of this LocalizationAssociationUpdate.  # noqa: E501
        :type: list[int]
        """

        self._localizations = localizations

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LocalizationAssociationUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, LocalizationAssociationUpdate):
            return True

        return self.to_dict() != other.to_dict()
